modLoader="javafml"
loaderVersion="${forge_loader_version}"
license="${mod_license}"
issueTrackerURL="${mod_repository}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="http://myurl.me/"
displayURL="${mod_homepage}"
logoFile="assets/${mod_id}/icon.png"
authors="${mod_author}"
description='''${mod_description}'''

# Dependencies
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="architectury"
mandatory=true
versionRange="[${min_architectury_version},)"
ordering="AFTER"
side="BOTH"
